[package]
name = "rust"
version = "0.1.0"
authors = ["Matthew <the10thwiz@gmail.com>"]
edition = "2018"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
rand = "0.7"
termion = "1.5"

