[package]
name = "rust"
version = "0.1.0"
authors = ["Matthew <the10thwiz@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
num-bigint = { version = "0.2", features = ["rand"] }
termion = "1.5"

